name: news_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: "<4.0.0"
dependencies:
  flutter:
    sdk: flutter
  pine:
    path: ../
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  retrofit: ^4.0.3
  dio: ^5.3.3
  equatable: ^2.0.5
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  retrofit_generator: ^8.0.4
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  bloc_test: ^9.1.5
  mockito: ^5.4.2
flutter:
  uses-material-design: true
