name: pine_annotations
description: A set of annotations for pine.
version: 2.0.0
repository: https://github.com/MyLittleSuite/pine
issue_tracker: https://github.com/MyLittleSuite/pine/issues
homepage: https://www.mylittlesuite.com

environment:
  sdk: ^3.5.4

dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
