name: pine
description: A lightweight architecture helper for your Flutter projects.
version: 2.0.0
repository: https://github.com/MyLittleSuite/pine
issue_tracker: https://github.com/MyLittleSuite/pine/issues
homepage: https://www.mylittlesuite.com

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
