name: pine_generator
description: A lightweight architecture helper for your Flutter projects.
version: 2.0.0
repository: https://github.com/MyLittleSuite/pine
issue_tracker: https://github.com/MyLittleSuite/pine/issues
homepage: https://www.mylittlesuite.com

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  analyzer: ^6.5.0
  build: ^2.4.1
  code_builder: ^4.10.0
  source_gen: ^1.5.0
  dart_style: ^2.3.4
  pine_annotations: ^2.0.0
  glob: ^2.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  source_gen_test: ^1.0.6
