name: Build Example

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      working-directory:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.platform == 'windows' && 'windows-latest' || contains('ios,macos', inputs.platform) && 'macos-latest' || 'ubuntu-latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup Flutter
        uses: ./.github/actions/setup
      - name: Set up JDK 17
        if: ${{ inputs.platform == 'android' }}
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Linux dependencies
        if: ${{ inputs.platform == 'linux' }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            clang cmake git \
            ninja-build pkg-config \
            libgtk-3-dev liblzma-dev \
            libstdc++-12-dev
      - name: Build Android
        if: ${{ inputs.platform == 'android' }}
        working-directory: ${{ inputs.working-directory }}
        run: flutter build apk --debug
      - name: Build iOS
        if: ${{ inputs.platform == 'ios' }}
        working-directory: ${{ inputs.working-directory }}
        run: flutter build ios --debug --no-codesign
      - name: Build Web
        if: ${{ inputs.platform == 'web' }}
        working-directory: ${{ inputs.working-directory }}
        run: flutter build web --release
      - name: Build Linux
        if: ${{ inputs.platform == 'linux' }}
        working-directory: ${{ inputs.working-directory }}
        run: flutter build linux --release
      - name: Build macOS
        if: ${{ inputs.platform == 'macos' }}
        working-directory: ${{ inputs.working-directory }}
        run: flutter build macos --release
      - name: Build Windows
        if: ${{ inputs.platform == 'windows' }}
        working-directory: ${{ inputs.working-directory }}
        run: flutter build windows --release
